// CoreDevice 506.6 固定 Swift schema 与已观察到的直接回信；只离线检查，无设备调用。
#include <cstdio>
#include <stop_token>
#include <string>

#include "remote/Device.h"
#include "remote/OrientationControl.h"
#include "xpc/XpcValue.h"

namespace {
int failures = 0;
int checks = 0;
void check(bool condition, const char *description) {
    ++checks;
    std::printf("[%s] %s\n", condition ? "PASS" : "FAIL", description);
    if (!condition) ++failures;
}
std::string hex(const std::vector<uint8_t> &bytes) {
    constexpr char alphabet[] = "0123456789abcdef";
    std::string result;
    for (const auto byte : bytes) {
        result += alphabet[byte >> 4];
        result += alphabet[byte & 15];
    }
    return result;
}
scrctl::xpc::Value state(std::string current, std::string nonflat, bool locked) {
    auto reply = scrctl::xpc::make_dict();
    scrctl::xpc::dict_set(reply, "currentDeviceOrientation", scrctl::xpc::make_string(std::move(current)));
    scrctl::xpc::dict_set(reply, "currentDeviceNonFlatOrientation", scrctl::xpc::make_string(std::move(nonflat)));
    scrctl::xpc::dict_set(reply, "currentDeviceOrientationLocked", scrctl::xpc::make_bool(locked));
    return reply;
}
} // namespace

int main() {
    using scrctl::remote::DeviceOrientation;
    using scrctl::remote::OrientationControl;
    using namespace scrctl::xpc;

    // Frozen query bytes from the independent static schema fixture, not generated by this class.
    constexpr const char *query_golden =
        "00f00000bc00000003000000666561747572654964656e746966696572000000009000003e000000"
        "636f6d2e6170706c652e636f72656465766963652e666561747572652e72656d6f74652e6465766963"
        "65636f6e74726f6c2e6f7269656e746174696f6e0000006d657373616765547970650000900000"
        "130000004f7269656e746174696f6e5265717565737400007061796c6f61640000f0000024000000"
        "0100000063757272656e744f7269656e746174696f6e000000f000000400000000000000";
    check(hex(encode(OrientationControl::build_query())) == query_golden, "query matches frozen schema bytes");
    for (const auto target : {DeviceOrientation::Portrait, DeviceOrientation::PortraitUpsideDown,
                              DeviceOrientation::LandscapeLeft, DeviceOrientation::LandscapeRight}) {
        const auto request = OrientationControl::build_change(target);
        check(request.has_value(), "all four cardinal targets accepted");
        if (!request) continue;
        std::string error;
        const auto decoded = decode(encode(*request), error);
        check(decoded && decoded->dict.size() == 3, "mutation has exactly three envelope fields after native codec");
        if (!decoded) continue;
        check(decoded->at("messageType").as_string_or() == "OrientationRequest" &&
                  decoded->at("featureIdentifier").as_string_or() == OrientationControl::kFeature,
              "direct OrientationRequest feature envelope");
        const auto &payload = decoded->at("payload");
        const auto &argument = payload.at("changeOrientation");
        check(payload.is_dict() && payload.dict.size() == 1 && argument.is_dict() &&
                  argument.dict.size() == 1 && argument.at("_0").as_string_or() == OrientationControl::name(target),
              "single changeOrientation associated value, no lock/restore field");
    }
    for (const auto value : {DeviceOrientation::Unknown, DeviceOrientation::FaceUp, DeviceOrientation::FaceDown,
                             static_cast<DeviceOrientation>(99)}) {
        check(!OrientationControl::build_change(value), "noncardinal mutation rejected before transport");
    }
    std::string error;
    const auto bytes = encode(state("faceUp", "portrait", false));
    const auto decoded = decode(bytes, error);
    const auto flat = decoded ? OrientationControl::parse_state(*decoded) : std::nullopt;
    check(flat && flat->current == DeviceOrientation::FaceUp && !flat->locked, "real faceUp/nonflat reply parses through native codec");
    check(flat && OrientationControl::effective_cardinal(*flat) == DeviceOrientation::Portrait,
          "flat phone uses nonflat baseline, not guessed physical direction");
    const auto cardinal = OrientationControl::parse_state(state("landscapeRight", "portrait", true));
    check(cardinal && OrientationControl::effective_cardinal(*cardinal) == DeviceOrientation::LandscapeRight &&
              cardinal->locked, "cardinal current wins and lock bool is preserved");
    const auto unknown = OrientationControl::parse_state(state("unknown", "faceDown", false));
    check(unknown && !OrientationControl::effective_cardinal(*unknown), "no cardinal baseline stays unknown");
    auto invalid = state("portrait", "portrait", false);
    dict_set(invalid, "currentDeviceOrientationLocked", make_string("false"));
    check(!OrientationControl::parse_state(invalid), "string boolean rejected");
    check(!OrientationControl::parse_state(state("rot90", "portrait", false)), "display rotation aliases are not device orientations");
    check(!OrientationControl::parse_state(state("portrait", "unrecognized", false)), "unknown enum rejected");
    invalid = state("portrait", "portrait", false);
    invalid.dict.pop_back();
    check(!OrientationControl::parse_state(invalid), "missing direct field rejected");
    invalid = state("portrait", "portrait", false);
    invalid.dict.push_back(invalid.dict.front());
    check(!OrientationControl::parse_state(invalid), "duplicate field rejected");
    invalid = make_dict();
    dict_set(invalid, "success", state("portrait", "portrait", false));
    check(!OrientationControl::parse_state(invalid), "unproven success wrapper rejected");
    invalid = state("portrait", "portrait", false);
    dict_set(invalid, "error", make_string("denied"));
    check(!OrientationControl::parse_state(invalid), "business error is not silently accepted as state");
    std::stop_source cancel;
    cancel.request_stop();
    scrctl::remote::Device no_session;
    check(!OrientationControl::connect(no_session, error, false, cancel.get_token()) && !error.empty(),
          "already cancelled connect returns before accessing device/RSD/transport");
    std::printf("%d checks, %d failures\n", checks, failures);
    return failures == 0 ? 0 : 1;
}
