#pragma once

#include <functional>
#include <optional>
#include <string>
#include <string_view>

#include "wifi/PairRecord.h"
#include "wifi/HostMetadata.h"
#include "wifi/Rppairing.h"

namespace scrctl::wifi {

struct PairableHostOptions {
    std::string host_identifier;
    std::string host_name;
    std::string host_model = std::string(wifi::host_model());
    std::string host_udid;
    Bytes host_alt_irk;       ///< Stable 16-byte identity advertised by the listener.
    Bytes host_private_key;   ///< Ed25519 seed, 32 bytes; must match host_public_key.
    Bytes host_public_key;    ///< Ed25519 public key, 32 bytes.
    std::string setup_pin;    ///< Six ASCII digits generated by the caller's CSPRNG.
    int64_t wire_protocol_version = 26;
    int64_t minimum_wire_protocol_version = 8;
};

/// Called after a valid M1, before sending the challenge. Do not log the PIN as
/// diagnostic evidence. False aborts this attempt; the callback supplies err.
using PairablePinCallback = std::function<bool(std::string_view pin, std::string &err)>;

struct PairableHostResult {
    PairRecord record;
    std::string peer_name;
    std::string peer_model;
};

/// Called only after M5 authentication, before emitting a successful M6.
/// Read-only admission may reject the authenticated peer with an error; it must
/// not publish a record. Host M6 identity fields need not be populated yet.
using PairableAdmissionCallback = std::function<bool(const PairableHostResult &, std::string &err)>;

/// Accept exactly one device-initiated handshake and SRP M1..M6 over an already
/// connected carrier. The phone is the protocol "host"; this responder is
/// "device". No sockets, advertisement, record writes, retries or rollback.
/// The caller owns transport deadlines/cancellation and the stable host keys.
///
/// M5 must authenticate its exact Identifier/LTPK with Controller-Sign and its
/// INFO must contain a UDID and 16-byte altIRK. Success means M6 was written,
/// not that the peer persisted trust. Before publishing the record, the caller
/// must reconnect normally, strictly PairVerify, and prevent old-record overwrite.
std::optional<PairableHostResult> accept_pairable_host(
    EnvelopeCarrier &carrier, const PairableHostOptions &options,
    const PairablePinCallback &display_pin, std::string &err,
    const PairableAdmissionCallback &admit = {});

}  // namespace scrctl::wifi
